apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:5.2.4
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      - name: kafka
        image: confluentinc/cp-kafka:5.3.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service.kafka.svc.cluster.local:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.kafka.svc.cluster.local:29092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-config
spec:
  containers:
  - name: kafka-init
    image: confluentinc/cp-kafka:5.3.1
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper-service.kafka.svc.cluster.local:2181
    volumeMounts:
    - name: kafka-config
      mountPath: /etc/scripts
    command: ['/bin/bash', '/etc/scripts/init-script.sh']
  volumes:
  - name: kafka-config
    configMap:
      name: kafka-config
      items:
      - key: init.sh
        path: init-script.sh
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - name: "9092"
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: "29092"
    protocol: TCP
    port: 29092
    targetPort: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - name: "2181"
    protocol: TCP
    port: 2181
    targetPort: 2181
