apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - ./nginx-deployment.yaml # just for testing http://localhost:31000
- ./namespaces.yaml
- ./monitoring
- ./kafka
- ./my-app
