apiVersion: apps/v1
kind: Deployment
metadata:
  name: astronauts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: astronauts-deployment
  template:
    metadata:
      labels:
        name: astronauts-deployment
    spec:
      containers:
        - name: astronauts-msvc
          image: k8s-astronauts-msvc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
          env:
            - name: UNIQUE_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_URL
              value: kafka-service.kafka.svc.cluster.local:9092
            - name: MONGO_URL
              value: mongodb://localhost:27017/astronauts-db
            - name: MONGO_DATABASE
              value: astronauts-db
            - name: PUBLIC_KEYS_PEM
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: public-keys-pem
        - name: astronauts-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: astronauts-service
spec:
  type: ClusterIP
  selector:
    name: astronauts-deployment
  ports:
    - protocol: TCP
      port: 8000
