apiVersion: apps/v1
kind: Deployment
metadata:
  name: astronauts-msvc-deployment
  labels:
    app: astronauts-msvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: astronauts-msvc
  template:
    metadata:
      labels:
        app: astronauts-msvc
    spec:
      containers:
      - name: astronauts-msvc
        image: eda-rust-astronauts-msvc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: UNIQUE_POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_URL
          value: kafka-service.kafka.svc.cluster.local:9092
        - name: MONGO_URL
          value: mongodb://localhost:27017/astronauts-db
        - name: MONGO_DATABASE
          value: astronauts-db
        - name: PUBLIC_KEYS_PEM
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4oghmhWVA6Ai/Z75BJQ9\nm4KTuwm+RY4ws/dpZswpOJcNG5Y1mDv21Tie+LWt3VrcyQei9HWU9GsGPNOTYZqE\nnstOYWiSMV90VVrjG+PAe98A21nvI5u+2F454XXb8IibzCysRw+pV1cAOs96s/6w\nZcA8FmRhIafXaqS772r4nOX0cm6yNCLemyz9k9oBFnFXPu5iyuj0k9Ll39+SHNXY\nk3nCj3BXW3bhoTyOxj4Nqp1nhssb/aezgrY1oHrqOZlaHWxPEh27D8tPqQgiKM1E\nWYPv8StQkuLDTw5Z4ofEkyjgZnpseqCAxmeixh3o3WemLNbGFLtKBjtRqxfFknR1\nfwIDAQAB\n-----END PUBLIC KEY-----\n
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: astronauts-msvc-service
spec:
  type: NodePort
  selector:
    app: astronauts-msvc
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 30002
