apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: auth-deployment
  template:
    metadata:
      labels:
        name: auth-deployment
    spec:
      containers:
      - name: auth-msvc
        image: k8s-auth-msvc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
        env:
        - name: UNIQUE_POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_URL
          value: kafka-service.kafka.svc.cluster.local:9092
        - name: MONGO_URL
          value: mongodb://localhost:27017/auth-db
        - name: MONGO_DATABASE
          value: auth-db
        - name: PUBLIC_KEYS_PEM
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: public-keys-pem
        - name: PRIVATE_KEY_PEM
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: private-key-pem
      - name: auth-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    name: auth-deployment
  ports:
  - protocol: TCP
    port: 8000
