apiVersion: apps/v1
kind: Deployment
metadata:
  name: missions-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: missions-deployment
  template:
    metadata:
      labels:
        name: missions-deployment
    spec:
      containers:
        - name: missions-msvc
          image: missions-msvc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: UNIQUE_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_URL
              value: kafka-service.kafka.svc.cluster.local:9092
            - name: MONGO_URL
              value: mongodb://localhost:27017/missions-db
            - name: MONGO_DATABASE
              value: missions-db
            - name: PUBLIC_KEYS_PEM
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: public-keys-pem
        - name: missions-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: missions-service
spec:
  type: ClusterIP
  selector:
    name: missions-deployment
  ports:
    - protocol: TCP
      port: 8000
